entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  RAILS_ENV: "production"

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  min_num_instances: 1
  max_num_instances: 1
