runtime: ruby32
env: standard
instance_class: F2
entrypoint: bundle exec rails server -p $PORT

env_variables:
  RAILS_ENV: "production"
  HOST: "ratemyskipper.uc.r.appspot.com"

beta_settings:
  cloud_sql_instances: 'ratemyskipper'

includes:
  - secrets.yaml