entrypoint: bundle exec rails db:migrate && bundle exec rails server -p $PORT # WE NEED TO TAKE THE MIGRATION OUT OF THIS LINE OUT FOR SURE
env: standard
runtime: ruby32

env_variables:
  RAILS_ENV: "production"
  HOST: "ratemyskipper.uc.r.appspot.com"

beta_settings:
  cloud_sql_instances: 'ratemyskipper'

includes:
  - secrets.yaml