entrypoint: bundle exec rails db:migrate && bundle exec rails server -p $PORT
env: standard
runtime: ruby32

env_variables:
  RAILS_ENV: "production"
  PORT: $PORT

beta_settings:
  cloud_sql_instances: 'ratemyskipper'

includes:
  - secrets.yaml