name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .env
        working-directory: server
        run: |
          cp .env.template .env
          sed -i 's/RAILS_ENV=/RAILS_ENV=production/' .env.production
          sed -i 's/RAILS_MASTER_KEY=/RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}/' .env.production
      - name: rsync deploy
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: server/
          remote_path: ~/server/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
      - name: SSH into server and restart api
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: docker restart api
# We'll want to restart the application after deploying, with 'docker restart api'
